### ISSUE TITLE
能添加内核仓库tag标签变量吗

### ISSUE THREAD

**Issue by buy404** [ophub/flippy-openwrt-actions#10]
你好，能否添加一个内核仓库tag变量，暴躁老哥的库现在不怎么更新了，想调用您的内核库，但是标签默认是kernel_stable，无法调用kernel_flippy，希望能添加一个设置使用内核的tag后缀的变量，谢谢

**Comment by ophub** [comment]
我刚去看了一下暴躁老哥的仓库，他的内核一直在稳定更新中，并没有断更，只有最新的一个内核没有上传，他可能忙，等等就更新了。

你打包的内核不是最新的版本也没明显的影响，一般来说内核版本的差异是无感的。

加tags选项很简单，我在我的另外2个armbian/openwrt里都有这个自定义选择，但由于暴躁老哥的仓库没有kernel_flippy等tags，所以加了这个选项后有人选其他的就会无法下载。我想了想还是不加了，会遭成不了解的人选错。

我想有一个简单一点的方法能满足你，就是自己维护一个内核仓库，自己更新自己打包节奏一致。你创建好仓库后，在Actions仓库选择列表里把你的添加上即可，这样就自主管理了，现在各行各业都流行自主可控。

**Comment by haiibo** [comment]
好的，我研究研究，感谢

**Comment by buy404** [comment]
好的，我研究研究，感谢
