### ISSUE TITLE
Login to OpenWrt → System → Amlogic Service → Install OpenWrt does not exist

### ISSUE THREAD

**Issue by snicoll** [ophub/flippy-openwrt-actions#12]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3] ARMv8 Processor x 7
 - Model [e.g. HK1] Radxa E52C

**OpenWrt Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100] 5.10.160-rk3588-flippy-2410a
 - Release: [e.g. official/lede/immortalwrt] lede

**Describe the bug | 问题描述**
The release notes of the latest version at the time of writing, https://github.com/ophub/flippy-openwrt-actions/releases/tag/OpenWrt_lede_save_2024.12, indicates that there is a way to install OpenWrt on EMMC. I am interested by that as I tried to upgrade using the iStoreOS OEM firmware upgrade and that broke it.

I've flashed https://github.com/ophub/flippy-openwrt-actions/releases/download/OpenWrt_lede_save_2024.12/openwrt_rk3588s_e52c_R24.10.24_k5.10.160-rk3588-flippy-2410a.img.gz on a SD card and I am able to boot. However, I don't see the "Install OpenWrt" button that is described in the release notes. What am I missing?

<img width="1306" alt="image" src="https://github.com/user-attachments/assets/3e3aafd9-16f8-4dd0-bb2a-45d22dcd9c23" />

**Comment by ophub** [comment]
The `amlogic` series can be installed online, but `rockchip` and `allwinner` do not need it.

**Comment by snicoll** [comment]
Sorry, I am not sure what that means. I am trying to install the version I booted on an SD card to the onboard EMMC. Is there any doc about that?

**Comment by ophub** [comment]
Radxa E52C：this is rockchip, use dd or rktool

**Comment by snicoll** [comment]
Thanks. I guess this can be closed, although I have no idea how to use `dd`.

**Comment by snicoll** [comment]
See https://forum.radxa.com/t/bricked-e52c-with-openwrt-flippy/25057/30?u=snicoll
