### ISSUE TITLE
希望增加黑豹x2的机型

### ISSUE THREAD

**Issue by xiaomeng9597** [ophub/flippy-openwrt-actions#9]
希望增加黑豹x2的机型，panther-x2，谢谢

**Comment by ophub** [comment]
已经有了，release里面下载

**Comment by xiaomeng9597** [comment]
> 已经有了，release里面下载

我是说flippy大的那个 OpenWrt_aarch64 没有黑豹x2

**Comment by ophub** [comment]
他好像没有添加这个机器，我刚去他仓库看了一下没发现这个的打包脚本。这个仓库的脚本只能打包f大支持的设备。
